import localFont from 'next/font/local';
import './globals.css';
import WhatsAppButton from './components/WhatsAppButton';
import { ModalProvider } from './Contexts/ModalContext';
import ProductModal from './components/ProductModal';
import NavBar from './components/Nav/NavBar';
import TopBar from './components/TopBar';
import Footer from './components/Sections/Footer';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <ModalProvider>
          <TopBar />
          <NavBar />
          {children}
          <Footer />
          <WhatsAppButton />
          <ProductModal />
        </ModalProvider>
      </body>
    </html>
  );
}
